settings:
  verbose: false
  project_root: ""

data:
  output_path: backend/data/output
  result_path: backend/data/result

input:
  name: "베이직 남성 회색 라운드 니트 스웨터"
  category: "니트/스웨터"
  price: 39800
  brand: "베이직웨어"
  features: "부드러운 촉감, 라운드 넥 디자인, 데일리 캐주얼 스타일, 보온성 우수"
  image_path: "data/input/product.jpg"
  css_type: 1