settings:
  verbose: false
  project_root: ""

data:
  output_path: backend/data/output
  result_path: backend/data/result

db_config:
  "host": "34.122.201.101"
  "user": "GEOGEO"
  "password": ""
  "db": "geo_db"

input:
  name: "민트 그린 썸머 나시 드레스"
  category: "여성의류 > 드레스 > 썸머드레스"
  price: 98000
  features: "상큼한 민트 그린 컬러의 가벼운 소재, 슬림핏 실루엣으로 여름 분위기 연출, 부드러운 나시 디자인으로 활동성 우수, 피크닉이나 데일리 외출에 적합"
  image_path: "backend/data/input/greendress.jpg"
  css_type: 1