settings:
  verbose: false
  project_root: /home/ubuntu/2025-GEO-Project
data:
  output_path: /home/ubuntu/2025-GEO-Project/backend/data/output
  result_path: /home/ubuntu/2025-GEO-Project/backend/data/result
input:
  name: "롤프 남성 정장자켓 수트마이 양복상의"
  category: "양복"
  price: 58000
  brand: "롤프"
  features: "꼼꼼한 박음질, 고급스러운 원단, 클래식한 디자인"
  ip_image_path: "backend/data/input/suit.jpg"
  model_image_path: "backend/data/input/a_man_posing_wearing_a_parakeet_t-shirt_removed_bg.png"
  mask_image_path: "backend/data/input/a_man_posing_wearing_a_parakeet_t-shirt_mask_upperbody.jpg"
  css_type: 1 # 1 or 2
  engine: "openai" # "openai" or "hf"

