data:
  output_path: backend/data/output
  result_path: backend/data/result

db_config:
  "host": "34.9.132.147"
  "user": "GEOGEO"
  "password": "GEOGEO1234!"
  "db": "geo_db"

input:
  name: "롤프 남성 정장자켓 수트마이 양복상하의"
  category: "양복"
  price: 58000
  brand: "롤프"
  features: "꼼꼼한 박음질, 고급스러운 원단, 클래식한 디자인"
  image_path_list: ["backend/data/input/suit.jpg", "backend/data/input/trousers.jpg"]
  css_type: 1 # 1 or 2
  engine: "openai" # "openai" or "hf"