settings:
  verbose: false
  project_root: /home/ubuntu/2025-GEO-Project
data:
  output_path: /home/ubuntu/2025-GEO-Project/backend/data/output
  result_path: /home/ubuntu/2025-GEO-Project/backend/data/result
input:
  name: 컴퓨터
  category: 한성
  price: 20000
  brand: 컴퓨터
  features: 최고
  css_type: 1
  image_path:
  - backend/data/input/product_0fd332a435114355b440727ffefdf40a_0.jpg
