settings:
  verbose: false
  project_root: /home/ubuntu/2025-GEO-Project
data:
  output_path: /home/ubuntu/2025-GEO-Project/backend/data/output
  result_path: /home/ubuntu/2025-GEO-Project/backend/data/result
db_config:
  host: ''
  user: GEOGEO
  password: ''
  db: geo_db
input:
  name: 롤프 남성 정장자켓 수트마이 양복상의
  category: 양복
  price: 58000
  brand: 롤프
  features: 꼼꼼한 박음질, 고급스러운 원단, 클래식한 디자인
  image_path_list:
  - backend/data/input/product_3cf493c11d2a4c7593e3e74d09eaaf65_0.jpg
  - backend/data/input/product_9d4dd1e9b366421f8afc83c677a52989_1.jpg
