name: myenv
channels:
  - pytorch
  - defaults
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - tqdm
  - pytorch
  - pillow
  - torchaudio
  - jupyterlab
  - torchvision
  - fastapi
  - uvicorn
  - pip:
      - langchain
      - transformers
      - openai
      - streamlit
      - requests
      - accelerate